
const cond=[["Anosmia","Ausência do olfato"],["Hiposmia","Redução da capacidade de sentir cheiros"],["Parosmia","Percepção distorcida dos odores"],["Fantosmia","Percepção de odores que não estão presentes"]];
const steps=[
["01","Avaliação médica especializada","Investigamos início, evolução, sintomas associados, doenças prévias e tratamentos já realizados."],
["02","Teste objetivo do olfato","A função olfatória é avaliada por teste padronizado para mensurar a alteração e estabelecer uma referência objetiva."],
["03","Investigação complementar","Quando necessário, solicitamos exames complementares para investigar possíveis causas e compreender melhor as vias nasais e olfatórias."],
["04","Tratamento individualizado","Definimos uma estratégia terapêutica individualizada, que pode envolver treinamento olfatório e outras modalidades quando indicadas."],
["05","Acompanhamento da evolução","Monitoramos sintomas, adesão e evolução com instrumentos estruturados de acompanhamento."],
["06","Reavaliação objetiva","Repetimos avaliações quando indicado para comparar resultados e orientar os próximos passos."]
];
export default function Home(){return <main>
<header><div className="wrap nav"><img src="/olfato-care-logo-white.png"/><nav><a href="#alteracoes">Alterações do olfato</a><a href="#como">Como funciona</a><a href="#evolucao">Acompanhamento</a><a href="#sobre">Sobre</a></nav><a className="outline" href="https://snot-22.olfatocare.com.br">Área do paciente</a></div></header>
<section className="hero"><div className="wrap heroGrid"><div><p className="eyebrow">Programa especializado em saúde olfatória</p><h1>Seu olfato mudou?<span>Nós ajudamos a entender por quê — e o que pode ser feito.</span></h1><p className="lead">Avaliação médica especializada, teste objetivo do olfato, investigação diagnóstica e tratamento individualizado.</p><p className="sig">AVALIAR · MEDIR · TRATAR · ACOMPANHAR</p><div className="actions"><a className="btn light" href="#como">Conheça o Olfato Care</a><a className="btn ghost" href="https://snot-22.olfatocare.com.br">Já sou paciente</a></div></div><div className="art"><div className="ring"/><div className="spark s1">✦</div><div className="spark s2">✧</div><p>Perceber aromas também é perceber memórias, sabores e experiências.</p></div></div></section>
<section id="alteracoes" className="section"><div className="wrap"><div className="heading"><div><p className="eyebrow blue">Quando o olfato muda</p><h2>A qualidade de vida também muda.</h2></div><p>O olfato participa da alimentação, da percepção de sabores, da segurança e do bem-estar. Alterações olfatórias podem ter diferentes causas e merecem investigação adequada.</p></div><div className="grid4">{cond.map(([a,b])=><article className="card" key={a}><div className="icon">◌</div><h3>{a}</h3><p>{b}</p></article>)}</div><p className="statement">Por isso, o primeiro passo não é simplesmente começar um tratamento: <b>é compreender o problema.</b></p></div></section>
<section id="como" className="section soft"><div className="wrap"><div className="center"><p className="eyebrow blue">Como funciona o Olfato Care</p><h2>Uma jornada estruturada, do diagnóstico ao acompanhamento.</h2></div><div className="steps">{steps.map(([n,t,d])=><article className="step" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
<section id="evolucao" className="section"><div className="wrap evolution"><div><p className="eyebrow blue">Evolução que se mede</p><h2>Não queremos apenas saber se você “acha que melhorou”.</h2><p>A percepção do paciente é essencial, mas pode ser combinada com avaliações objetivas e instrumentos estruturados.</p><ul><li><b>Teste olfatório</b> — avaliação objetiva da função olfatória.</li><li><b>SNOT-22</b> — impacto dos sintomas nasossinusais e qualidade de vida.</li><li><b>Histórico de evolução</b> — resultados registrados ao longo do tempo.</li></ul></div><div className="chart"><h3>Exemplo de evolução</h3><svg viewBox="0 0 520 240"><line x1="50" x2="490" y1="190" y2="190"/><line x1="50" x2="490" y1="140" y2="140"/><line x1="50" x2="490" y1="90" y2="90"/><polyline points="60,70 205,105 350,145 480,175"/>{[[60,70,78],[205,105,62],[350,145,41],[480,175,24]].map(([x,y,v])=><g key={v}><circle cx={x} cy={y} r="6"/><text x={x} y={y-12}>{v}</text></g>)}</svg><small>* Exemplo ilustrativo. A evolução varia entre pessoas.</small></div></div></section>
<section className="section soft"><div className="wrap grid4">{[["Avaliar","Compreender a causa provável e o contexto clínico."],["Medir","Mensurar a função olfatória e acompanhar a evolução."],["Tratar","Definir estratégias individualizadas e baseadas em evidências."],["Acompanhar","Registrar a evolução para apoiar decisões em cada etapa."]].map(([a,b])=><article className="value" key={a}><i/><h3>{a}</h3><p>{b}</p></article>)}</div></section>
<section id="sobre" className="section"><div className="wrap about"><div className="badge">OTORRINOLARINGOLOGIA<br/>SAÚDE OLFATÓRIA</div><div><p className="eyebrow blue">Quem está por trás do Olfato Care</p><h2>Medicina, ciência e acompanhamento individualizado.</h2><p>O Olfato Care integra avaliação médica, mensuração objetiva, investigação complementar, tratamento e acompanhamento da evolução.</p><h3>Dr. Gilberto Luiz Pereira da Silva Neto</h3><p>Médico otorrinolaringologista</p></div></div></section>
<section className="cta"><div className="wrap ctaGrid"><div><p className="eyebrow">Seu olfato mudou?</p><h2>O primeiro passo é descobrir o que está acontecendo.</h2><p>A indicação e o tratamento são definidos individualmente após avaliação médica.</p></div><a className="btn light" href="#contato">Agendar uma avaliação</a></div></section>
<section id="contato" className="contact"><div className="wrap">Para agendamento, entre em contato com a equipe Olfato Care. Em breve conectaremos este botão ao canal definitivo de atendimento.</div></section>
<footer><div className="wrap foot"><img src="/olfato-care-logo-white.png"/><p>Avaliar. Medir. Tratar. Acompanhar.</p><a href="https://snot-22.olfatocare.com.br">Área do paciente</a></div></footer>
</main>}
